### ISSUE TITLE
Edit a segment's geometry

### ISSUE THREAD

**Issue by theolampert** [henrymoews/ptransformapp#7]
~It should be possible to edit a `LineString` geometry and persist it.~

~An idea for interaction:~
~1. Select a LineString~
~2. Drag handles, delete handles if necissary~
~3. Press save?~
~4. send `PUT` to `/segments/{id}`~
~5. Update segment with response~

Changes to segment geometry should be persisted to the backend

**Comment by henrymoews** [comment]
@theolampert You don't think the current interaction is okay? 
![grafik](https://user-images.githubusercontent.com/8428849/102328619-95b90e80-3f87-11eb-8a64-201821d1b1b9.png)

You can delete handles by a double click. We just don't save the changed shape yet.

**Comment by theolampert** [comment]
@henrymoews I totally missed this! yes this makes sense, I'll update the issue

**Comment by theolampert** [comment]
Ah what I meant was that you could delete and already persisted line, that doesn't look like it's supported yet but perhaps we can leave it off for now?

**Comment by henrymoews** [comment]
We can hide the deletion button, yes. The lib supports this out of the box. I'll check and change.

**Comment by henrymoews** [comment]
So, but how do we lines then? I mean, we should support this from the beginning, shouldn't we?

**Comment by theolampert** [comment]
Yes, either just delete it and redraw it or be able to edit it somehow

**Comment by henrymoews** [comment]
I updated PTMap and disabled / hid the deletion button
